basePath: /
consumes:
    - application/json
definitions:
    BaseDataInfo:
        description: The basic response with data | 基础带数据信息
        properties:
            code:
                description: Error code | 错误代码
                format: int64
                type: integer
                x-go-name: Code
            data:
                description: Data | 数据
                type: string
                x-go-name: Data
            msg:
                description: Message | 提示信息
                type: string
                x-go-name: Msg
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    BaseIDInfo:
        description: The base ID response data | 基础ID信息
        properties:
            createdAt:
                description: Create date | 创建日期
                format: int64
                type: integer
                x-go-name: CreatedAt
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: Id
            updatedAt:
                description: Update date | 更新日期
                format: int64
                type: integer
                x-go-name: UpdatedAt
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    BaseListInfo:
        description: The basic response with data | 基础带数据信息
        properties:
            data:
                description: Data | 数据
                type: string
                x-go-name: Data
            total:
                description: The total number of data | 数据总数
                format: uint64
                type: integer
                x-go-name: Total
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    BaseMsgResp:
        description: The basic response without data | 基础不带数据信息
        properties:
            code:
                description: Error code | 错误代码
                format: int64
                type: integer
                x-go-name: Code
            msg:
                description: Message | 提示信息
                type: string
                x-go-name: Msg
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    BaseUUIDInfo:
        description: The base UUID response data | 基础UUID信息
        properties:
            createdAt:
                description: Create date | 创建日期
                format: int64
                type: integer
                x-go-name: CreatedAt
            id:
                description: ID
                type: string
                x-go-name: Id
            updatedAt:
                description: Update date | 更新日期
                format: int64
                type: integer
                x-go-name: UpdatedAt
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    IDPathReq:
        description: Basic ID request | 基础ID地址参数请求
        properties:
            Id:
                description: ID
                format: uint64
                type: integer
        required:
            - Id
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    IDReq:
        description: Basic ID request | 基础ID参数请求
        properties:
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: Id
        required:
            - id
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    IDsReq:
        description: Basic IDs request | 基础ID数组参数请求
        properties:
            ids:
                description: IDs
                items:
                    format: uint64
                    type: integer
                type: array
                x-go-name: Ids
        required:
            - ids
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    PageInfo:
        description: The page request parameters | 列表请求参数
        properties:
            page:
                description: Page number | 第几页
                format: uint64
                type: integer
                x-go-name: Page
            pageSize:
                description: Page size | 单页数据行数
                format: uint64
                maximum: 100000
                type: integer
                x-go-name: PageSize
        required:
            - page
            - pageSize
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    StudentInfo:
        description: The response data of student information | Student信息
        properties:
            age:
                description: Age
                format: int64
                type: integer
                x-go-name: Age
            ageInt:
                description: AgeInt
                format: int64
                type: integer
                x-go-name: AgeInt
            ageInt8:
                description: AgeInt8
                format: int8
                type: integer
                x-go-name: AgeInt8
            ageInt16:
                description: AgeInt16
                format: int16
                type: integer
                x-go-name: AgeInt16
            ageInt32:
                description: AgeInt32
                format: int32
                type: integer
                x-go-name: AgeInt32
            ageInt64:
                description: AgeInt64
                format: int64
                type: integer
                x-go-name: AgeInt64
            ageUint:
                description: AgeUint
                format: uint64
                type: integer
                x-go-name: AgeUint
            ageUint8:
                description: AgeUint8
                format: uint8
                type: integer
                x-go-name: AgeUint8
            ageUint16:
                description: AgeUint16
                format: uint16
                type: integer
                x-go-name: AgeUint16
            ageUint32:
                description: AgeUint32
                format: uint32
                type: integer
                x-go-name: AgeUint32
            ageUint64:
                description: AgeUint64
                format: uint64
                type: integer
                x-go-name: AgeUint64
            classId:
                description: ClassId
                type: string
                x-go-name: ClassId
            createdAt:
                description: Create date | 创建日期
                format: int64
                type: integer
                x-go-name: CreatedAt
            enrollAt:
                description: EnrollAt
                format: int64
                type: integer
                x-go-name: EnrollAt
            id:
                description: ID
                format: uint64
                type: integer
                x-go-name: Id
            name:
                description: Name
                type: string
                x-go-name: Name
            statusBool:
                description: StatusBool
                type: boolean
                x-go-name: StatusBool
            teacherId:
                description: TeacherId
                format: uint64
                type: integer
                x-go-name: TeacherId
            updatedAt:
                description: Update date | 更新日期
                format: int64
                type: integer
                x-go-name: UpdatedAt
            weightFloat:
                description: WeightFloat
                format: double
                type: number
                x-go-name: WeightFloat
            weightFloat32:
                description: WeightFloat32
                format: float
                type: number
                x-go-name: WeightFloat32
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    StudentInfoResp:
        description: Student information response | Student信息返回体
        properties:
            code:
                description: Error code | 错误代码
                format: int64
                type: integer
                x-go-name: Code
            data:
                $ref: '#/definitions/StudentInfo'
                description: Data | 数据
                type: string
                x-go-name: Data
            msg:
                description: Message | 提示信息
                type: string
                x-go-name: Msg
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    StudentListInfo:
        description: Student list data | Student列表数据
        properties:
            data:
                description: The API list data | Student列表数据
                items:
                    $ref: '#/definitions/StudentInfo'
                type: array
                x-go-name: Data
            total:
                description: The total number of data | 数据总数
                format: uint64
                type: integer
                x-go-name: Total
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    StudentListReq:
        description: Get student list request params | Student列表请求参数
        properties:
            name:
                description: Name
                type: string
                x-go-name: Name
            page:
                description: Page number | 第几页
                format: uint64
                type: integer
                x-go-name: Page
            pageSize:
                description: Page size | 单页数据行数
                format: uint64
                maximum: 100000
                type: integer
                x-go-name: PageSize
        required:
            - page
            - pageSize
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    StudentListResp:
        description: The response data of student list | Student列表数据
        properties:
            code:
                description: Error code | 错误代码
                format: int64
                type: integer
                x-go-name: Code
            data:
                $ref: '#/definitions/StudentListInfo'
                description: Data | 数据
                type: string
                x-go-name: Data
            msg:
                description: Message | 提示信息
                type: string
                x-go-name: Msg
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    UUIDReq:
        description: Basic UUID request | 基础UUID参数请求
        properties:
            id:
                description: ID
                maxLength: 36
                type: string
                x-go-name: Id
        required:
            - id
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
    UUIDsReq:
        description: Basic UUID array request | 基础UUID数组参数请求
        properties:
            ids:
                description: Ids
                items:
                    type: string
                type: array
                x-go-name: Ids
        required:
            - ids
        type: object
        x-go-package: github.com/suyuan32/simple-admin-example-api/internal/types
host: localhost:8081
info:
    description: 'Description: example service'
    title: example
    version: 0.0.1
paths:
    /init/database:
        get:
            description: Initialize database | 初始化数据库
            operationId: InitDatabase
            responses:
                "200":
                    description: BaseMsgResp
                    schema:
                        $ref: '#/definitions/BaseMsgResp'
            summary: Initialize database | 初始化数据库
            tags:
                - base
    /student:
        post:
            description: Get student by ID | 通过ID获取Student
            operationId: GetStudentById
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/IDReq'
                    type: object
            responses:
                "200":
                    description: StudentInfoResp
                    schema:
                        $ref: '#/definitions/StudentInfoResp'
            summary: Get student by ID | 通过ID获取Student
            tags:
                - student
    /student/create:
        post:
            description: Create student information | 创建Student
            operationId: CreateStudent
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/StudentInfo'
                    type: object
            responses:
                "200":
                    description: BaseMsgResp
                    schema:
                        $ref: '#/definitions/BaseMsgResp'
            summary: Create student information | 创建Student
            tags:
                - student
    /student/delete:
        post:
            description: Delete student information | 删除Student信息
            operationId: DeleteStudent
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/IDsReq'
                    type: object
            responses:
                "200":
                    description: BaseMsgResp
                    schema:
                        $ref: '#/definitions/BaseMsgResp'
            summary: Delete student information | 删除Student信息
            tags:
                - student
    /student/list:
        post:
            description: Get student list | 获取Student列表
            operationId: GetStudentList
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/StudentListReq'
                    type: object
            responses:
                "200":
                    description: StudentListResp
                    schema:
                        $ref: '#/definitions/StudentListResp'
            summary: Get student list | 获取Student列表
            tags:
                - student
    /student/update:
        post:
            description: Update student information | 更新Student
            operationId: UpdateStudent
            parameters:
                - in: body
                  name: body
                  schema:
                    $ref: '#/definitions/StudentInfo'
                    type: object
            responses:
                "200":
                    description: BaseMsgResp
                    schema:
                        $ref: '#/definitions/BaseMsgResp'
            summary: Update student information | 更新Student
            tags:
                - student
produces:
    - application/json
responses:
    SimpleMsg:
        description: The simplest message | 最简单的信息
        headers:
            msg:
                description: Message | 信息
                type: string
schemes:
    - http
    - https
security:
    - Token:
        - '[]'
securityDefinitions:
    Token:
        in: header
        name: Authorization
        type: apiKey
swagger: "2.0"
